version: '3.7'

services:
  maven:
    build:
      context: ./maven
      dockerfile: Dockerfile
    container_name: download
    working_dir: /root/maven
    volumes:
      - /c/Users/Public/repos/artifactory/maven:/root/maven
    tty: true

  gradle:
    build:
      context: ./gradle
      dockerfile: Dockerfile
    container_name: upload
    working_dir: /root/gradle
    volumes:
      - /c/Users/Public/repos/artifactory/gradle:/root/gradle
    tty: true

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.2.1
    container_name: artifactory
    volumes:
      - artifactory7_data:/var/opt/jfrog/artifactory
    ports:
      - "8081:8081"
      - "8082:8082"

volumes:
  # Named volume
  artifactory7_data:
